### ISSUE TITLE
Error enum not public

### ISSUE THREAD

**Issue by 18AX** [ftdi-rs/ftdi-embedded-hal#29]
I am looking to create a wrapper around the crate but I do not understand how am I supposed to use the `Error` enum since the module is not public.

```rs
// Cannot return use Error because the module error is private
fn init_spi<T: MpsseCmdExecutor>(hal: FtHal<T>) -> Result<(), ????> {
    let spi = hal.spi()?;
    let pin = hal.ad6()?

    Ok(())
}
```

**Comment by newAM** [comment]
That's definitely not intentional, I'll see if I can get a fix out tomorrow :)

**Comment by 18AX** [comment]
Great ! thank you
